# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20160208_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', related_query_name='activity', to='cal.Event'),
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='process',
            field=models.ManyToManyField(blank=True, related_name='events', related_query_name='event', to='cal.Process'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='events', related_query_name='event', to='cal.Tag'),
        ),
        migrations.AlterField(
            model_name='process',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='processes', related_query_name='process', to='cal.Theme'),
        ),
    ]
