# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20160208_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start', 'title'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['start', 'title'], 'verbose_name_plural': 'processes'},
        ),
    ]
