# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0004_auto_20160208_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.BigIntegerField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STATUS_ACTIVE', 'STATUS_ACTIVE'), ('STATUS_DONE', 'STATUS_DONE'), ('STATUS_FAILED', 'STATUS_FAILED'), ('STATUS_SUSPENDED', 'STATUS_SUSPENDED'), ('STATUS_UNDEFINED', 'STATUS_UNDEFINED')], default='STATUS_UNDEFINED', max_length=255)),
                ('start', models.DateField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('end', models.DateField()),
                ('startIsMilestone', models.BooleanField(default=False)),
                ('endIsMilestone', models.BooleanField(default=False)),
                ('depends', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('assignee', models.ManyToManyField(blank=True, related_name='tasks', related_query_name='task', to='cal.Assignee')),
            ],
            options={
                'ordering': ['start', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='holder',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='level',
            new_name='focus',
        ),
        migrations.RemoveField(
            model_name='event',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='event',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to='cal.Event'),
        ),
        migrations.AddField(
            model_name='assignee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.Role'),
        ),
    ]
