# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20160210_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hasChild',
            field=models.BooleanField(default=False),
        ),
    ]
