# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_task_haschild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='effort',
            field=models.BigIntegerField(default=0),
        ),
    ]
