# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
    ]
