# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_remove_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end',
            field=models.DateField(),
        ),
    ]
