# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_auto_20160211_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True),
        ),
    ]
