# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_auto_20160211_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(),
        ),
    ]
