# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_auto_20160211_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='purpose',
            new_name='objectives',
        ),
    ]
