# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_auto_20160212_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='objectives_approved',
            field=models.BooleanField(default=False),
        ),
    ]
