# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_auto_20160212_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='focus',
            field=models.CharField(choices=[('AT', 'Attending'), ('PR', 'Presenting'), ('SE', 'Organising side event'), ('LR', 'Launching report'), ('MO', 'Monitoring'), ('MF', 'Monitoring and follow-up'), ('RE', 'Remotely engage')], default='MO', max_length=2),
        ),
    ]
