# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0018_auto_20160223_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
