# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0022_auto_20160229_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='%Y/%m/%d/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#BA0C2F', 'Red'), ('#FFFFFF', 'White'), ('#000000', 'Black'), ('#EA7600', 'Orange'), ('#93328E', 'Purple'), ('#1B365D', 'Blue'), ('#0095CB', 'Light-blue')], default='#1B365D', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='event_URL',
            field=models.URLField(blank=True, max_length=1027, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='events', related_query_name='event', to='cal.Attachment'),
        ),
    ]
