# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0023_auto_20160304_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
