# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0024_auto_20160304_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#BA0C2F', 'Red'), ('#FFFFFF', 'White'), ('#EA7600', 'Orange'), ('#93328E', 'Purple'), ('#1B365D', 'Blue'), ('#0095CB', 'Light-blue')], default='#1B365D', max_length=7),
        ),
    ]
