# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_auto_20160304_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='events', related_query_name='event', to='cal.Theme'),
        ),
        migrations.AddField(
            model_name='event',
            name='funders',
            field=models.ManyToManyField(blank=True, to='cal.Funder'),
        ),
    ]
