# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0028_auto_20160309_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='upload',
            field=models.FileField(max_length=500, upload_to='%Y/%m/%d/'),
        ),
    ]
