# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0031_auto_20160321_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cross_Cutting_Area',
            new_name='CrossCuttingArea',
        ),
    ]
