# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0032_auto_20160321_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
