# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0034_auto_20160321_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#BA0C2F', 'Red: Leadership team meetings'), ('#EA7600', 'Orange: Tony and Judith meeting'), ('#93328E', 'Purple: Global days'), ('#1B365D', 'Blue: external event or meeting'), ('#0095CB', 'Light-blue: Policy process milestones')], default='#1B365D', max_length=7),
        ),
    ]
