# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0035_auto_20160321_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('#BA0C2F', 'Leadership team meetings'), ('#EA7600', 'Tony and Judith meeting'), ('#93328E', 'Global days'), ('#1B365D', 'External event or meeting'), ('#0095CB', 'Policy process milestones')], default='#1B365D', max_length=7),
        ),
    ]
