# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0036_auto_20160321_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['modified']},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='title',
        ),
    ]
