# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0037_auto_20160321_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='focus',
            field=models.CharField(choices=[('AT', 'Attending'), ('MO', 'Monitoring'), ('RE', 'Remotely engage')], default='MO', max_length=2),
        ),
    ]
